export { Header } from "./Header";
export { Hero } from "./Hero";
export { IntroSection } from "./IntroSection";
export { ServicesSection } from "./ServicesSection";
export { ProcessSection } from "./ProcessSection";
export { IndustriesSection } from "./IndustriesSection";
export { TestimonialsSection } from "./TestimonialsSection";
export { CTASection } from "./CTASection";
export { Footer } from "./Footer";
